### ISSUE TITLE
Volumes with `cloudstor:azure` driver prevent changing permissions on files

### ISSUE THREAD

**Issue by vovimayhem** [docker/for-azure#15]
Whenever I try to use the `cloudstor:azure` driver on a volume intended to be used on a container that changes the file ownership of the mounted files, the files never get assigned to the new owner.

Observed cases: Running `postgres` or `rabbitmq` with the data volume using the `cloudstor:azure` will always fail. Both have entrypoint scripts that try to ensure the data files belong to a different user. 

### Expected behavior

Changing the ownership of files inside a `cloudstor:azure` volume should be successful.

### Actual behavior

Trying to change the ownership of files inside a `cloudstor:azure` volume fails silently.

### Information

 - Running `docker-diagnose` failed with `Error: No such object: meta-azure`

### Steps to reproduce the behavior

Given the following compose file:

```
# stack.yml
version: '3.1'

volumes:
  data:
    driver: cloudstor:azure

services:
  rabbitmq:
    image: rabbitmq:3.6-alpine
    volumes: [ "data:/var/lib/rabbitmq" ]
```

1. Deploy the stack: `docker stack deploy --compose-file stack.yml rabbit`
2. Observe the service failing to start: `watch -n 2 docker stack ps rabbit`
