### ISSUE TITLE
Not able to share cloudstor azure named volumes across multiple containers on same host

### ISSUE THREAD

**Issue by kevinlisota** [docker/for-azure#68]
We are using the cloudstor azure driver to persist files across multiple containers and hosts. 

Previously, we used the Microsoft Azure docker driver, which has been abandoned in favor of cloudstor.

We have two containers, one nginx and one php, that run on two hosts. We do not use swarm mode.

The latest cloudstor driver is installed, and the driver works fine in a single container. However, when trying to mount the same named volume in a second container on the same host, we get this error:

```
ERROR: for nginx  Cannot start service nginx: error while mounting volume '/var/lib/docker/plugins/56f927ed3c5aa4a507db1f1671fb219c78a393ad721f82fe01cc46c2c33364ce/propagated-mount/cloudstor/uploads-production': VolumeDriver.Mount: mount failed: exit status 32
output="mount error(16): Resource busy\nRefer to the mount.cifs(8) manual page (e.g. man mount.cifs)\nmount: mounting //foobar.file.core.windows.net/foobar-production on /mnt/cloudstor/uploads-production failed: Resource busy\n"
```

Our docker compose file looks like this, which is what brings up the two containers on each host. The cloudstor azure volume was created using `docker volume create` and does propagate across hosts. We do not use swarm.
```
version: '3.6'
services:
  nginx:
    container_name: nginx
    image: foobar.azurecr.io/foobar/nginx:v3.0
    depends_on:
        - php
    ports:
        - "80:80"
        - "443:443"
    sysctls:
        - net.core.somaxconn=1024
    restart: always
    volumes:
        - /datadrive/foobar-production:/var/www/foobar.com/
        - uploads-production:/var/www/foobar.com/wp-content/uploads/
        - /mnt/fastcgicache:/fastcgicache
  php:
    container_name: php
    image: foobar.azurecr.io/foobar/php:v3.0
    ports:
        - "9000:9000"
    sysctls:
        - net.core.somaxconn=1024
    restart: always
    volumes:
        - /datadrive/foobar-production:/var/www/foobar.com/
        - uploads-production:/var/www/foobar.com/wp-content/uploads/
volumes:
    uploads-production:
        external: true
```

The /datadrive is a local mount which works fine. `uploads-production` is an Azure File share meant to be shared across containers and hosts using the cloudstor Azure driver.
