### ISSUE TITLE
Mongodb failed to run with persisted volume with cloudstor plugin.

### ISSUE THREAD

**Issue by egzonzeneli** [docker/for-azure#75]
### Expected behavior

Mount a persisted volume through cloudstor:azure plugin under mongodb swarm task under /data/db path.

### Actual behavior

Task failed with fassert under wiredtiger . I googled and it seems is a known problem with SMB FileStorage. But my initial thoughts after reading [cloudstor:azure](https://docs.docker.com/docker-for-azure/persistent-data-volumes/) that plugin somehow will map correct permission of users group and make things work.

### Information

**docker version**
Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

**cloudstor version**
18.06.1-ce-azure2

here is my docker-compose.yml sample 
```yaml
version '3.7'

services:
 mongodb: 
    command: mongod
    image: mongo
    volumes:
      - 'mongodb-pd:/data/db:rw'

volumes:
  mongodb-pd:
    driver: cloudstor:azure
    driver_opts:
      share: mongo-db-test
      uid: 999
      gid: 999
      filemode: 0777
      dirmode: 0777

```
I tried every combination of properties under driver_opts ....
